on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: latex
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add msttcorefonts-installer
            update-ms-fonts
            fc-cache -f
            for i in statement/*.tex; do filename=$(basename "$i" .tex); lualatex -jobname="$filename" build_all_biosketches.tex done
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: 'Biosketchs'
          path: ./*.pdf
            
