name: Build and Release Biosketches

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Compile LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add msttcorefonts-installer
            update-ms-fonts
            fc-cache -f
            for i in statement/*.tex; do 
              filename=$(basename "$i" .tex)
              lualatex -jobname="$filename" build_all_biosketches
            done
      
      - name: Rename PDFs with prefix
        run: |
          mkdir -p release_pdfs
          for pdf in *.pdf; do
            cp "$pdf" "release_pdfs/macalpine_$pdf"
          done
      
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Biosketches'
          path: ./release_pdfs/*.pdf
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release_pdfs/*.pdf
          name: Biosketch Release ${{ steps.date.outputs.date }}
          tag_name: release-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}